// cp1_6.14_auto106/src/components/ControlPanel.vue
<template>
  <div class="control-panel">
    <h3 class="panel-title">环境参数控制</h3>

    <div class="sliders-container">
      <div class="slider-group">
        <div class="slider-header">
          <span class="slider-label">
            <span class="slider-icon light">☀</span>
            光照强度
          </span>
          <span
            class="slider-value"
            :style="{ color: getValueColor(params.light, [60, 85]) }"
          >
            {{ Math.round(params.light) }}%
          </span>
        </div>
        <div class="slider-track-wrapper">
          <input
            type="range"
            min="0"
            max="100"
            step="1"
            :value="params.light"
            @input="e => throttledLight(Number((e.target as HTMLInputElement).value))"
            class="custom-slider light-slider"
          />
        </div>
        <div class="slider-status">
          <span class="status-tag" :class="getStatusClass(params.light, [60, 85])">
            {{ getStatusText(params.light, [60, 85]) }}
          </span>
        </div>
      </div>

      <div class="slider-group">
        <div class="slider-header">
          <span class="slider-label">
            <span class="slider-icon water">💧</span>
            水分供应
          </span>
          <span
            class="slider-value"
            :style="{ color: getValueColor(params.water, [40, 65]) }"
          >
            {{ Math.round(params.water) }}%
          </span>
        </div>
        <div class="slider-track-wrapper">
          <input
            type="range"
            min="0"
            max="100"
            step="1"
            :value="params.water"
            @input="e => throttledWater(Number((e.target as HTMLInputElement).value))"
            class="custom-slider water-slider"
          />
        </div>
        <div class="slider-status">
          <span class="status-tag" :class="getStatusClass(params.water, [40, 65])">
            {{ getStatusText(params.water, [40, 65]) }}
          </span>
        </div>
      </div>

      <div class="slider-group">
        <div class="slider-header">
          <span class="slider-label">
            <span class="slider-icon temp">🌡</span>
            环境温度
          </span>
          <span
            class="slider-value"
            :style="{ color: getValueColor(params.temperature, [50, 75]) }"
          >
            {{ Math.round(params.temperature) }}%
          </span>
        </div>
        <div class="slider-track-wrapper">
          <input
            type="range"
            min="0"
            max="100"
            step="1"
            :value="params.temperature"
            @input="e => throttledTemp(Number((e.target as HTMLInputElement).value))"
            class="custom-slider temp-slider"
          />
        </div>
        <div class="slider-status">
          <span class="status-tag" :class="getStatusClass(params.temperature, [50, 75])">
            {{ getStatusText(params.temperature, [50, 75]) }}
          </span>
        </div>
      </div>

      <div class="slider-group">
        <div class="slider-header">
          <span class="slider-label">
            <span class="slider-icon nutrient">🌱</span>
            土壤养分
          </span>
          <span
            class="slider-value"
            :style="{ color: getValueColor(params.nutrients, [40, 70]) }"
          >
            {{ Math.round(params.nutrients) }}%
          </span>
        </div>
        <div class="slider-track-wrapper">
          <input
            type="range"
            min="0"
            max="100"
            step="1"
            :value="params.nutrients"
            @input="e => throttledNutrients(Number((e.target as HTMLInputElement).value))"
            class="custom-slider nutrient-slider"
          />
        </div>
        <div class="slider-status">
          <span class="status-tag" :class="getStatusClass(params.nutrients, [40, 70])">
            {{ getStatusText(params.nutrients, [40, 70]) }}
          </span>
        </div>
      </div>
    </div>

    <div class="quick-presets">
      <span class="presets-label">快速预设</span>
      <div class="preset-buttons">
        <button class="preset-btn" @click="applyPreset('rainforest')">雨林</button>
        <button class="preset-btn" @click="applyPreset('desert')">沙漠</button>
        <button class="preset-btn" @click="applyPreset('temperate')">温带</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { EnvironmentParams } from '@/types'
import { throttle, getHealthColor, getHealthStatus } from '@/utils/helpers'

interface Props {
  params: EnvironmentParams
}

const props = defineProps<Props>()

const emit = defineEmits<{
  (e: 'update:params', params: EnvironmentParams): void
  (e: 'change', params: Partial<EnvironmentParams>): void
}>()

const throttledLight = throttle((v: number) => emit('change', {light: v}), 100)
const throttledWater = throttle((v: number) => emit('change', {water: v}), 100)
const throttledTemp = throttle((v: number) => emit('change', {temperature: v}), 100)
const throttledNutrients = throttle((v: number) => emit('change', {nutrients: v}), 100)

function getValueColor(value: number, optimal: [number, number]): string {
  const [min, max] = optimal
  if (value < min * 0.7) return '#ef4444'
  if (value < min) return '#f97316'
  if (value <= max) return '#22c55e'
  if (value <= max * 1.2) return '#f97316'
  return '#ef4444'
}

function getStatusClass(value: number, optimal: [number, number]): string {
  const [min, max] = optimal
  if (value < min * 0.7 || value > max * 1.3) return 'danger'
  if (value < min || value > max) return 'warning'
  return 'good'
}

function getStatusText(value: number, optimal: [number, number]): string {
  const [min, max] = optimal
  if (value < min * 0.7) return '严重不足'
  if (value < min) return '偏低'
  if (value > max * 1.3) return '严重过量'
  if (value > max) return '偏高'
  return '适宜'
}

function applyPreset(preset: string) {
  let newParams: Partial<EnvironmentParams> = {}

  switch (preset) {
    case 'rainforest':
      newParams = { light: 70, water: 85, temperature: 75, nutrients: 80 }
      break
    case 'desert':
      newParams = { light: 95, water: 15, temperature: 85, nutrients: 30 }
      break
    case 'temperate':
      newParams = { light: 65, water: 50, temperature: 55, nutrients: 55 }
      break
  }

  emit('change', newParams)
}
</script>

<style scoped>
.control-panel {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.panel-title {
  font-size: 14px;
  font-weight: 600;
  color: #e2e8f0;
  margin: 0;
}

.sliders-container {
  display: flex;
  flex-direction: column;
  gap: 18px;
}

.slider-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.slider-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.slider-label {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  color: #cbd5e1;
  font-weight: 500;
}

.slider-icon {
  font-size: 14px;
}

.slider-value {
  font-size: 14px;
  font-weight: 700;
  font-variant-numeric: tabular-nums;
  transition: color 0.3s ease;
}

.slider-track-wrapper {
  position: relative;
  height: 8px;
}

.custom-slider {
  -webkit-appearance: none;
  appearance: none;
  width: 100%;
  height: 8px;
  border-radius: 4px;
  outline: none;
  cursor: pointer;
  background: transparent;
}

.custom-slider::-webkit-slider-runnable-track {
  height: 8px;
  border-radius: 4px;
  background: linear-gradient(to right, #3b82f6, #22c55e, #ef4444);
}

.custom-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 18px;
  height: 18px;
  border-radius: 50%;
  background: #ffffff;
  border: 2px solid #60a5fa;
  cursor: pointer;
  margin-top: -5px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
  transition: all 0.2s ease;
}

.custom-slider::-webkit-slider-thumb:hover {
  transform: scale(1.15);
  box-shadow: 0 2px 12px rgba(96, 165, 250, 0.5);
}

.custom-slider::-moz-range-track {
  height: 8px;
  border-radius: 4px;
  background: linear-gradient(to right, #3b82f6, #22c55e, #ef4444);
}

.custom-slider::-moz-range-thumb {
  width: 18px;
  height: 18px;
  border-radius: 50%;
  background: #ffffff;
  border: 2px solid #60a5fa;
  cursor: pointer;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
  transition: all 0.2s ease;
}

.custom-slider::-moz-range-thumb:hover {
  transform: scale(1.15);
}

.slider-status {
  display: flex;
  justify-content: flex-end;
}

.status-tag {
  font-size: 10px;
  font-weight: 600;
  padding: 2px 8px;
  border-radius: 10px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.status-tag.good {
  background: rgba(34, 197, 94, 0.15);
  color: #4ade80;
}

.status-tag.warning {
  background: rgba(249, 115, 22, 0.15);
  color: #fb923c;
}

.status-tag.danger {
  background: rgba(239, 68, 68, 0.15);
  color: #f87171;
}

.quick-presets {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding-top: 8px;
  border-top: 1px solid rgba(255, 255, 255, 0.1);
}

.presets-label {
  font-size: 11px;
  color: #64748b;
  font-weight: 500;
}

.preset-buttons {
  display: flex;
  gap: 8px;
}

.preset-btn {
  flex: 1;
  padding: 8px 12px;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  color: #94a3b8;
  font-size: 11px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease;
}

.preset-btn:hover {
  background: rgba(255, 255, 255, 0.1);
  color: #e2e8f0;
  border-color: rgba(255, 255, 255, 0.2);
}
</style>

// cp2_6.21_auto44/temp_repo/cp1_6.19_auto344/src/components/ControlPanel.tsx
import { useExhibitStore } from '@/store/exhibitStore';
import { Sun, Thermometer, RotateCcw } from 'lucide-react';

export default function ControlPanel() {
  const { lightConfig, updateLightAngle, updateLightColorTemp, resetExhibits } = useExhibitStore();

  const handleAngleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    updateLightAngle(parseFloat(e.target.value));
  };

  const handleColorTempChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    updateLightColorTemp(parseFloat(e.target.value));
  };

  return (
    <div className="control-panel">
      <h3 className="panel-title">灯光控制</h3>
      
      <div className="control-group">
        <div className="control-label">
          <RotateCcw size={16} />
          <span>光源角度</span>
          <span className="value">{lightConfig.angle.toFixed(0)}°</span>
        </div>
        <input
          type="range"
          min="0"
          max="360"
          value={lightConfig.angle}
          onChange={handleAngleChange}
          className="custom-slider"
        />
        <div className="slider-labels">
          <span>0°</span>
          <span>180°</span>
          <span>360°</span>
        </div>
      </div>

      <div className="control-group">
        <div className="control-label">
          <Thermometer size={16} />
          <span>色温调节</span>
          <span className="value">{lightConfig.colorTemp.toFixed(0)}K</span>
        </div>
        <input
          type="range"
          min="2700"
          max="6500"
          step="100"
          value={lightConfig.colorTemp}
          onChange={handleColorTempChange}
          className="custom-slider temp-slider"
        />
        <div className="slider-labels">
          <span>暖色 2700K</span>
          <span>冷色 6500K</span>
        </div>
      </div>

      <div className="color-preview">
        <div className="preview-label">光源颜色预览</div>
        <div 
          className="color-circle" 
          style={{ backgroundColor: lightConfig.color }}
        />
      </div>

      <button className="reset-btn" onClick={resetExhibits}>
        重置展品位置
      </button>

      <style>{`
        .control-panel {
          position: fixed;
          right: 24px;
          top: 50%;
          transform: translateY(-50%);
          width: 280px;
          padding: 24px;
          background: rgba(255, 255, 255, 0.12);
          backdrop-filter: blur(6px);
          -webkit-backdrop-filter: blur(6px);
          border-radius: 8px;
          border: 1px solid rgba(255, 255, 255, 0.1);
          color: white;
          z-index: 1000;
        }

        .panel-title {
          margin: 0 0 20px 0;
          font-size: 18px;
          font-weight: 600;
          letter-spacing: 0.5px;
          text-align: center;
          color: #4FC3F7;
        }

        .control-group {
          margin-bottom: 24px;
        }

        .control-label {
          display: flex;
          align-items: center;
          gap: 8px;
          margin-bottom: 12px;
          font-size: 14px;
          color: #e0e0e0;
        }

        .control-label .value {
          margin-left: auto;
          font-weight: 600;
          color: #4FC3F7;
        }

        .custom-slider {
          width: 100%;
          height: 4px;
          -webkit-appearance: none;
          appearance: none;
          background: #333;
          border-radius: 2px;
          outline: none;
          cursor: pointer;
        }

        .custom-slider::-webkit-slider-thumb {
          -webkit-appearance: none;
          appearance: none;
          width: 16px;
          height: 16px;
          background: #fff;
          border: 2px solid #4FC3F7;
          border-radius: 50%;
          cursor: pointer;
          transition: all 0.2s ease;
        }

        .custom-slider::-webkit-slider-thumb:hover {
          transform: scale(1.1);
          box-shadow: 0 0 10px rgba(79, 195, 247, 0.5);
        }

        .custom-slider::-moz-range-thumb {
          width: 16px;
          height: 16px;
          background: #fff;
          border: 2px solid #4FC3F7;
          border-radius: 50%;
          cursor: pointer;
          transition: all 0.2s ease;
        }

        .custom-slider::-moz-range-thumb:hover {
          transform: scale(1.1);
          box-shadow: 0 0 10px rgba(79, 195, 247, 0.5);
        }

        .custom-slider:active::-webkit-slider-thumb {
          background: #4FC3F7;
        }

        .temp-slider {
          background: linear-gradient(to right, #ff8a00, #ffffff, #87ceeb);
        }

        .slider-labels {
          display: flex;
          justify-content: space-between;
          font-size: 11px;
          color: #888;
          margin-top: 6px;
        }

        .color-preview {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 12px;
          background: rgba(0, 0, 0, 0.2);
          border-radius: 6px;
          margin-bottom: 16px;
        }

        .preview-label {
          font-size: 12px;
          color: #aaa;
        }

        .color-circle {
          width: 32px;
          height: 32px;
          border-radius: 50%;
          border: 2px solid rgba(255, 255, 255, 0.3);
          box-shadow: 0 0 15px currentColor;
          transition: background-color 0.3s ease;
        }

        .reset-btn {
          width: 100%;
          padding: 10px 16px;
          background: #333;
          color: white;
          border: none;
          border-radius: 6px;
          font-size: 14px;
          cursor: pointer;
          transition: all 0.2s ease;
        }

        .reset-btn:hover {
          background: #555;
        }

        @media (max-width: 768px) {
          .control-panel {
            display: none;
          }
        }
      `}</style>
    </div>
  );
}
