// cp2_6.22_auto56/repo/cp2_6.21_auto44/temp_repo/cp4_6.15_auto132/temp_repo/cp1_6.14_auto84/src/components/ControlPanel.vue
<template>
  <div class="control-panel">
    <div class="panel-title">Flow Control</div>

    <div class="control-group">
      <div class="control-header">
        <span class="control-label">节点数量</span>
        <span class="control-value">{{ nodeCount }}</span>
      </div>
      <div class="slider-track">
        <div class="slider-fill" :style="{ width: ((nodeCount - 10) / 20 * 100) + '%' }"></div>
        <input
          type="range"
          :min="10"
          :max="30"
          :value="nodeCount"
          @input="onNodeCountChange"
          class="slider-input"
        />
      </div>
    </div>

    <div class="control-group">
      <div class="control-header">
        <span class="control-label">流动速度</span>
        <span class="control-value">{{ flowSpeed }}</span>
      </div>
      <div class="slider-track">
        <div class="slider-fill" :style="{ width: ((flowSpeed - 1) / 9 * 100) + '%' }"></div>
        <input
          type="range"
          :min="1"
          :max="10"
          :value="flowSpeed"
          @input="onFlowSpeedChange"
          class="slider-input"
        />
      </div>
    </div>

    <div class="control-group">
      <div class="control-header">
        <span class="control-label">颜色主题</span>
      </div>
      <select :value="colorTheme" @change="onThemeChange" class="theme-select">
        <option value="cyberpunk">赛博朋克青紫</option>
        <option value="warm">暖橙火焰</option>
        <option value="fresh">清新蓝绿</option>
      </select>
    </div>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  nodeCount: number
  flowSpeed: number
  colorTheme: string
}>()

const emit = defineEmits<{
  'update:nodeCount': [value: number]
  'update:flowSpeed': [value: number]
  'update:colorTheme': [value: string]
}>()

function onNodeCountChange(e: Event) {
  emit('update:nodeCount', Number((e.target as HTMLInputElement).value))
}

function onFlowSpeedChange(e: Event) {
  emit('update:flowSpeed', Number((e.target as HTMLInputElement).value))
}

function onThemeChange(e: Event) {
  emit('update:colorTheme', (e.target as HTMLSelectElement).value)
}
</script>

<style scoped>
.control-panel {
  position: fixed;
  bottom: 24px;
  right: 24px;
  width: 320px;
  padding: 20px;
  background: rgba(26, 26, 46, 0.75);
  backdrop-filter: blur(16px);
  -webkit-backdrop-filter: blur(16px);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 12px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4), 0 0 1px rgba(255, 255, 255, 0.1);
  z-index: 200;
  color: rgba(255, 255, 255, 0.85);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  font-size: 13px;
}

.panel-title {
  font-size: 15px;
  font-weight: 600;
  margin-bottom: 18px;
  letter-spacing: 0.5px;
  color: rgba(255, 255, 255, 0.95);
  text-transform: uppercase;
}

.control-group {
  margin-bottom: 16px;
}

.control-group:last-child {
  margin-bottom: 0;
}

.control-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.control-label {
  font-size: 12px;
  color: rgba(255, 255, 255, 0.6);
  letter-spacing: 0.3px;
}

.control-value {
  font-size: 13px;
  font-weight: 600;
  color: rgba(255, 255, 255, 0.9);
  font-family: 'Courier New', monospace;
  min-width: 24px;
  text-align: right;
}

.slider-track {
  position: relative;
  width: 100%;
  height: 6px;
  background: rgba(255, 255, 255, 0.08);
  border-radius: 3px;
  overflow: hidden;
}

.slider-fill {
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  background: linear-gradient(90deg, rgba(0, 255, 255, 0.5), rgba(157, 0, 255, 0.5));
  border-radius: 3px;
  transition: width 0.15s ease;
  pointer-events: none;
}

.slider-input {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 0;
  cursor: pointer;
  margin: 0;
}

.theme-select {
  width: 100%;
  padding: 8px 12px;
  background: rgba(255, 255, 255, 0.06);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  color: rgba(255, 255, 255, 0.85);
  font-size: 13px;
  font-family: inherit;
  outline: none;
  cursor: pointer;
  appearance: none;
  -webkit-appearance: none;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='rgba(255,255,255,0.5)' d='M6 8L1 3h10z'/%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-position: right 12px center;
  transition: border-color 0.2s, background-color 0.2s;
}

.theme-select:hover {
  border-color: rgba(255, 255, 255, 0.2);
  background-color: rgba(255, 255, 255, 0.09);
}

.theme-select:focus {
  border-color: rgba(0, 255, 255, 0.4);
}

.theme-select option {
  background: #1a1a2e;
  color: rgba(255, 255, 255, 0.85);
}
</style>

// cp2_6.21_auto44/temp_repo/cp1_6.19_auto344/src/components/ControlPanel.tsx
import { useExhibitStore } from '@/store/exhibitStore';
import { Sun, Thermometer, RotateCcw } from 'lucide-react';

export default function ControlPanel() {
  const { lightConfig, updateLightAngle, updateLightColorTemp, resetExhibits } = useExhibitStore();

  const handleAngleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    updateLightAngle(parseFloat(e.target.value));
  };

  const handleColorTempChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    updateLightColorTemp(parseFloat(e.target.value));
  };

  return (
    <div className="control-panel">
      <h3 className="panel-title">灯光控制</h3>
      
      <div className="control-group">
        <div className="control-label">
          <RotateCcw size={16} />
          <span>光源角度</span>
          <span className="value">{lightConfig.angle.toFixed(0)}°</span>
        </div>
        <input
          type="range"
          min="0"
          max="360"
          value={lightConfig.angle}
          onChange={handleAngleChange}
          className="custom-slider"
        />
        <div className="slider-labels">
          <span>0°</span>
          <span>180°</span>
          <span>360°</span>
        </div>
      </div>

      <div className="control-group">
        <div className="control-label">
          <Thermometer size={16} />
          <span>色温调节</span>
          <span className="value">{lightConfig.colorTemp.toFixed(0)}K</span>
        </div>
        <input
          type="range"
          min="2700"
          max="6500"
          step="100"
          value={lightConfig.colorTemp}
          onChange={handleColorTempChange}
          className="custom-slider temp-slider"
        />
        <div className="slider-labels">
          <span>暖色 2700K</span>
          <span>冷色 6500K</span>
        </div>
      </div>

      <div className="color-preview">
        <div className="preview-label">光源颜色预览</div>
        <div 
          className="color-circle" 
          style={{ backgroundColor: lightConfig.color }}
        />
      </div>

      <button className="reset-btn" onClick={resetExhibits}>
        重置展品位置
      </button>

      <style>{`
        .control-panel {
          position: fixed;
          right: 24px;
          top: 50%;
          transform: translateY(-50%);
          width: 280px;
          padding: 24px;
          background: rgba(255, 255, 255, 0.12);
          backdrop-filter: blur(6px);
          -webkit-backdrop-filter: blur(6px);
          border-radius: 8px;
          border: 1px solid rgba(255, 255, 255, 0.1);
          color: white;
          z-index: 1000;
        }

        .panel-title {
          margin: 0 0 20px 0;
          font-size: 18px;
          font-weight: 600;
          letter-spacing: 0.5px;
          text-align: center;
          color: #4FC3F7;
        }

        .control-group {
          margin-bottom: 24px;
        }

        .control-label {
          display: flex;
          align-items: center;
          gap: 8px;
          margin-bottom: 12px;
          font-size: 14px;
          color: #e0e0e0;
        }

        .control-label .value {
          margin-left: auto;
          font-weight: 600;
          color: #4FC3F7;
        }

        .custom-slider {
          width: 100%;
          height: 4px;
          -webkit-appearance: none;
          appearance: none;
          background: #333;
          border-radius: 2px;
          outline: none;
          cursor: pointer;
        }

        .custom-slider::-webkit-slider-thumb {
          -webkit-appearance: none;
          appearance: none;
          width: 16px;
          height: 16px;
          background: #fff;
          border: 2px solid #4FC3F7;
          border-radius: 50%;
          cursor: pointer;
          transition: all 0.2s ease;
        }

        .custom-slider::-webkit-slider-thumb:hover {
          transform: scale(1.1);
          box-shadow: 0 0 10px rgba(79, 195, 247, 0.5);
        }

        .custom-slider::-moz-range-thumb {
          width: 16px;
          height: 16px;
          background: #fff;
          border: 2px solid #4FC3F7;
          border-radius: 50%;
          cursor: pointer;
          transition: all 0.2s ease;
        }

        .custom-slider::-moz-range-thumb:hover {
          transform: scale(1.1);
          box-shadow: 0 0 10px rgba(79, 195, 247, 0.5);
        }

        .custom-slider:active::-webkit-slider-thumb {
          background: #4FC3F7;
        }

        .temp-slider {
          background: linear-gradient(to right, #ff8a00, #ffffff, #87ceeb);
        }

        .slider-labels {
          display: flex;
          justify-content: space-between;
          font-size: 11px;
          color: #888;
          margin-top: 6px;
        }

        .color-preview {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 12px;
          background: rgba(0, 0, 0, 0.2);
          border-radius: 6px;
          margin-bottom: 16px;
        }

        .preview-label {
          font-size: 12px;
          color: #aaa;
        }

        .color-circle {
          width: 32px;
          height: 32px;
          border-radius: 50%;
          border: 2px solid rgba(255, 255, 255, 0.3);
          box-shadow: 0 0 15px currentColor;
          transition: background-color 0.3s ease;
        }

        .reset-btn {
          width: 100%;
          padding: 10px 16px;
          background: #333;
          color: white;
          border: none;
          border-radius: 6px;
          font-size: 14px;
          cursor: pointer;
          transition: all 0.2s ease;
        }

        .reset-btn:hover {
          background: #555;
        }

        @media (max-width: 768px) {
          .control-panel {
            display: none;
          }
        }
      `}</style>
    </div>
  );
}
