// cp1_6.14_auto106/src/components/GrowthLog.vue
<template>
  <div class="growth-log">
    <h3 class="log-title">生长日志</h3>

    <div class="log-container" ref="logContainerRef">
      <div v-if="logs.length === 0" class="empty-state">
        <span class="empty-icon">📝</span>
        <span class="empty-text">暂无生长记录</span>
      </div>

      <div
        v-for="(log, index) in logs"
        :key="log.id"
        class="log-item"
        :class="{ 'log-enter': isNewLog(log.id) }"
        :style="{ animationDelay: index * 0.05 + 's' }"
      >
        <div class="log-timeline">
          <span class="timeline-dot" :class="log.type"></span>
          <span class="timeline-line" v-if="index < logs.length - 1"></span>
        </div>

        <div class="log-content">
          <span class="log-time">{{ formatTime(log.timestamp) }}</span>
          <p class="log-message" :class="log.type">{{ log.message }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, nextTick } from 'vue'
import type { GrowthLogEntry } from '@/types'
import { formatTime } from '@/utils/helpers'

interface Props {
  logs: GrowthLogEntry[]
}

const props = defineProps<Props>()

const logContainerRef = ref<HTMLElement | null>(null)
const newLogIds = ref<Set<string>>(new Set())

function isNewLog(id: string): boolean {
  return newLogIds.value.has(id)
}

watch(
  () => props.logs,
  (newLogs, oldLogs) => {
    if (newLogs.length > (oldLogs?.length || 0)) {
      const newIds = newLogs.slice(0, newLogs.length - (oldLogs?.length || 0)).map(l => l.id)
      newIds.forEach(id => newLogIds.value.add(id))

      setTimeout(() => {
        newIds.forEach(id => newLogIds.value.delete(id))
      }, 1000)

      nextTick(() => {
        if (logContainerRef.value) {
          logContainerRef.value.scrollTop = 0
        }
      })
    }
  },
  { deep: true }
)
</script>

<style scoped>
.growth-log {
  display: flex;
  flex-direction: column;
  gap: 12px;
  height: 100%;
}

.log-title {
  font-size: 14px;
  font-weight: 600;
  color: #e2e8f0;
  margin: 0;
  flex-shrink: 0;
}

.log-container {
  flex: 1;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding-right: 8px;
  min-height: 0;
}

.log-container::-webkit-scrollbar {
  width: 4px;
}

.log-container::-webkit-scrollbar-track {
  background: rgba(255, 255, 255, 0.05);
  border-radius: 2px;
}

.log-container::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.2);
  border-radius: 2px;
}

.log-container::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.3);
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 32px 16px;
  color: #64748b;
}

.empty-icon {
  font-size: 32px;
  opacity: 0.5;
}

.empty-text {
  font-size: 12px;
}

.log-item {
  display: flex;
  gap: 12px;
  position: relative;
}

.log-item.log-enter {
  animation: slideIn 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

@keyframes slideIn {
  from {
    opacity: 0;
    transform: translateX(20px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

.log-timeline {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 16px;
  flex-shrink: 0;
  padding-top: 4px;
}

.timeline-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  flex-shrink: 0;
  background: #64748b;
  box-shadow: 0 0 8px currentColor;
}

.timeline-dot.info {
  background: #60a5fa;
  box-shadow: 0 0 8px #60a5fa;
}

.timeline-dot.success {
  background: #4ade80;
  box-shadow: 0 0 8px #4ade80;
}

.timeline-dot.warning {
  background: #fbbf24;
  box-shadow: 0 0 8px #fbbf24;
}

.timeline-dot.danger {
  background: #f87171;
  box-shadow: 0 0 8px #f87171;
}

.timeline-line {
  width: 2px;
  flex: 1;
  background: rgba(255, 255, 255, 0.1);
  margin-top: 4px;
}

.log-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 2px;
  padding-bottom: 12px;
}

.log-time {
  font-size: 10px;
  color: #64748b;
  font-variant-numeric: tabular-nums;
}

.log-message {
  font-size: 12px;
  color: #cbd5e1;
  margin: 0;
  line-height: 1.4;
}

.log-message.info {
  color: #93c5fd;
}

.log-message.success {
  color: #86efac;
}

.log-message.warning {
  color: #fcd34d;
}

.log-message.danger {
  color: #fca5a5;
}
</style>

// cp2_6.20_auto54/src/components/GrowthLog.tsx
import React from 'react';
import dayjs from 'dayjs';
import { GrowthLogEntry, ActionType } from '../types';

interface GrowthLogProps {
  logs: GrowthLogEntry[];
  plantedAt: number;
}

const getActionIcon = (action: ActionType): string => {
  switch (action) {
    case ActionType.PLANT:
      return '🌱';
    case ActionType.WATER:
      return '💧';
    case ActionType.FERTILIZE:
      return '✨';
    default:
      return '📝';
  }
};

const getActionLabel = (action: ActionType): string => {
  switch (action) {
    case ActionType.PLANT:
      return '种植';
    case ActionType.WATER:
      return '浇水';
    case ActionType.FERTILIZE:
      return '施肥';
    default:
      return '操作';
  }
};

export const GrowthLog: React.FC<GrowthLogProps> = ({ logs, plantedAt }) => {
  const sortedLogs = [...logs].sort((a, b) => b.timestamp - a.timestamp);

  return (
    <div className="growth-log-container">
      <div className="log-planting-info">
        <span className="planting-label">种植时间</span>
        <span className="planting-time">{dayjs(plantedAt).format('YYYY-MM-DD HH:mm:ss')}</span>
      </div>
      <div className="log-timeline">
        <div className="log-header">
          <span className="log-title">📋 生长日志</span>
          <span className="log-count">共 {logs.length} 条记录</span>
        </div>
        <div className="log-list">
          {sortedLogs.length === 0 ? (
            <div className="log-empty">暂无记录</div>
          ) : (
            sortedLogs.map((log) => (
              <div key={log.id} className="log-item">
                <div className="log-dot" />
                <div className="log-content">
                  <div className="log-top-row">
                    <span className="log-action">
                      <span className="log-icon">{getActionIcon(log.action)}</span>
                      <span className="log-action-label">{getActionLabel(log.action)}</span>
                    </span>
                    <span className="log-time">{dayjs(log.timestamp).format('HH:mm:ss')}</span>
                  </div>
                  <div className="log-desc">{log.description}</div>
                  <div className="log-date">{dayjs(log.timestamp).format('YYYY-MM-DD')}</div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
      <style>{`
        .growth-log-container {
          padding: 12px 4px 4px;
          border-top: 1px solid #e8e0d0;
        }
        .log-planting-info {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 8px 12px;
          background: linear-gradient(90deg, #f5e6a344, transparent);
          border-radius: 8px;
          margin-bottom: 12px;
        }
        .planting-label {
          font-size: 12px;
          color: #8b6f47;
          font-weight: 500;
        }
        .planting-time {
          font-size: 13px;
          color: #5a8f4c;
          font-weight: 600;
          font-family: 'Courier New', monospace;
        }
        .log-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 12px;
          padding: 0 4px;
        }
        .log-title {
          font-size: 14px;
          font-weight: 600;
          color: #5a8f4c;
        }
        .log-count {
          font-size: 11px;
          color: #999;
        }
        .log-list {
          max-height: 240px;
          overflow-y: auto;
          padding-right: 4px;
        }
        .log-list::-webkit-scrollbar {
          width: 4px;
        }
        .log-list::-webkit-scrollbar-thumb {
          background: #5a8f4c44;
          border-radius: 2px;
        }
        .log-item {
          display: flex;
          gap: 12px;
          padding: 8px 0;
          animation: log-fade-in 0.3s ease;
        }
        @keyframes log-fade-in {
          from {
            opacity: 0;
            transform: translateY(-4px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        .log-dot {
          width: 10px;
          height: 10px;
          border-radius: 50%;
          background: #5a8f4c;
          margin-top: 6px;
          flex-shrink: 0;
          box-shadow: 0 0 0 3px #5a8f4c22;
          position: relative;
        }
        .log-item:not(:last-child) .log-dot::after {
          content: '';
          position: absolute;
          top: 14px;
          left: 4px;
          width: 2px;
          height: calc(100% + 8px);
          background: #e8e0d0;
        }
        .log-content {
          flex: 1;
          min-width: 0;
        }
        .log-top-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 2px;
        }
        .log-action {
          display: flex;
          align-items: center;
          gap: 4px;
        }
        .log-icon {
          font-size: 14px;
        }
        .log-action-label {
          font-size: 12px;
          font-weight: 600;
          color: #333;
        }
        .log-time {
          font-size: 11px;
          color: #999;
          font-family: 'Courier New', monospace;
        }
        .log-desc {
          font-size: 12px;
          color: #666;
          margin-bottom: 2px;
        }
        .log-date {
          font-size: 10px;
          color: #bbb;
        }
        .log-empty {
          text-align: center;
          padding: 24px;
          color: #ccc;
          font-size: 13px;
        }
      `}</style>
    </div>
  );
};
