// cp1_6.22_auto256/src/components/SkeletonCard.vue
<template>
  <div class="skeleton-card">
    <div class="skeleton-line skeleton-header"></div>
    <div class="skeleton-line skeleton-short"></div>
    <div class="skeleton-line skeleton-medium"></div>
    <div class="skeleton-line skeleton-short"></div>
    <div class="skeleton-progress"></div>
  </div>
</template>

<script setup lang="ts">
</script>

<style scoped>
.skeleton-card {
  height: 200px;
  background: #fff;
  border-radius: 12px;
  padding: 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}

.skeleton-line {
  background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
  background-size: 200% 100%;
  animation: shimmer 1.5s infinite;
  border-radius: 4px;
  margin-bottom: 12px;
}

.skeleton-header {
  height: 24px;
  width: 70%;
}

.skeleton-short {
  height: 16px;
  width: 40%;
}

.skeleton-medium {
  height: 16px;
  width: 60%;
}

.skeleton-progress {
  height: 8px;
  width: 100%;
  background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
  background-size: 200% 100%;
  animation: shimmer 1.5s infinite;
  border-radius: 4px;
  margin-top: 20px;
}

@keyframes shimmer {
  0% {
    background-position: 200% 0;
  }
  100% {
    background-position: -200% 0;
  }
}
</style>

// cp2_6.22_auto56/repo/cp1_6.20_auto10/src/components/SkeletonCard.tsx
const SkeletonCard = () => {
  return (
    <div
      style={{
        borderRadius: '12px',
        overflow: 'hidden',
        backgroundColor: '#1e1e2e',
        border: '1px solid #313244',
      }}
    >
      <div
      style={{
        width: '100%',
        height: '180px',
        background: 'linear-gradient(90deg, #313244 25%, #45475a 50%, #313244 75%)',
        backgroundSize: '200% 100%',
        animation: 'pulse 1.5s infinite',
      }}
    />
    <div style={{ padding: '16px' }}>
      <div
        style={{
          height: '24px',
          width: '70%',
          borderRadius: '4px',
          background: 'linear-gradient(90deg, #313244 25%, #45475a 50%, #313244 75%)',
          backgroundSize: '200% 100%',
          animation: 'pulse 1.5s infinite',
          marginBottom: '12px',
        }}
      />
      <div
        style={{
          height: '20px',
          width: '40%',
          borderRadius: '4px',
          background: 'linear-gradient(90deg, #313244 25%, #45475a 50%, #313244 75%)',
          backgroundSize: '200% 100%',
          animation: 'pulse 1.5s infinite',
          marginBottom: '12px',
        }}
      />
      <div
        style={{
          display: 'flex',
          gap: '16px',
        }}
      >
        <div
          style={{
            height: '16px',
            width: '60px',
            borderRadius: '4px',
            background: 'linear-gradient(90deg, #313244 25%, #45475a 50%, #313244 75%)',
            backgroundSize: '200% 100%',
            animation: 'pulse 1.5s infinite',
          }}
        />
        <div
          style={{
            height: '16px',
            width: '60px',
            borderRadius: '4px',
            background: 'linear-gradient(90deg, #313244 25%, #45475a 50%, #313244 75%)',
            backgroundSize: '200% 100%',
            animation: 'pulse 1.5s infinite',
          }}
        />
      </div>
    </div>
    <style>{`
      @keyframes pulse {
        0% { background-position: 200% 0; }
        100% { background-position: -200% 0; }
      }
    `}</style>
  </div>
  );
};

export default SkeletonCard;
