// cp1_6.14_auto66/src/components/SongCard.vue
<script setup lang="ts">
import type { Song } from '@/types'

interface Props {
  song: Song
  selected: boolean
}

const props = defineProps<Props>()
const emit = defineEmits<{
  (e: 'select', song: Song): void
}>()

const genreLabel: Record<string, string> = {
  pop: '流行',
  folk: '民谣',
  electronic: '电子'
}
</script>

<template>
  <div
    class="song-card relative shrink-0 w-[220px] h-[300px] rounded-2xl overflow-hidden cursor-pointer transition-all duration-300"
    :class="{
      'scale-110 z-10': selected,
      'hover:scale-105 hover:-translate-y-2': !selected
    }"
    @click="emit('select', props.song)"
  >
    <!-- Gradient Cover -->
    <div
      class="absolute inset-0"
      :style="{ background: props.song.coverGradient }"
    />
    <!-- Overlay pattern -->
    <div class="absolute inset-0 bg-black/20" />
    <div class="absolute inset-0 opacity-30"
         style="background-image: radial-gradient(circle at 30% 30%, rgba(255,255,255,0.3), transparent 60%);" />

    <!-- Content -->
    <div class="relative z-10 flex flex-col h-full p-5">
      <div class="flex items-start justify-between">
        <span
          class="px-2 py-1 rounded-md text-[10px] font-medium text-white/90 backdrop-blur-sm"
          style="background: rgba(255,255,255,0.15); text-shadow: 0 0 8px rgba(255,255,255,0.3);"
        >
          {{ genreLabel[props.song.genre] }}
        </span>
        <div
          v-if="selected"
          class="w-6 h-6 rounded-full bg-white/90 flex items-center justify-center"
          style="box-shadow: 0 0 15px rgba(255,255,255,0.6);"
        >
          <svg viewBox="0 0 24 24" width="14" height="14" fill="#667eea">
            <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/>
          </svg>
        </div>
      </div>

      <div class="flex-1 flex items-center justify-center">
        <svg viewBox="0 0 64 64" width="72" height="72" fill="rgba(255,255,255,0.85)" style="filter: drop-shadow(0 0 20px rgba(255,255,255,0.4))">
          <path d="M48 5a2 2 0 0 0-2-2 2 2 0 0 0-2 2v13.4l-18.2-3.4a2 2 0 0 0-2.4 1.9L23.4 27a2 2 0 0 0 1.6 2.4l18 3.4c0.3 0.1 0.5 0.1 0.8 0.1a2 2 0 0 0 1.9-1.5l2.6-13.7A2 2 0 0 0 48 14V5zM24 40c-4.4 0-8 3.1-8 7s3.6 7 8 7 8-3.1 8-7-3.6-7-8-7zm26-12c-4.4 0-8 3.1-8 7s3.6 7 8 7 8-3.1 8-7-3.6-7-8-7z"/>
        </svg>
      </div>

      <div>
        <h3
          class="text-xl font-bold text-white mb-1"
          style="text-shadow: 0 2px 12px rgba(0,0,0,0.5), 0 0 20px rgba(255,255,255,0.2);"
        >
          {{ props.song.title }}
        </h3>
        <p class="text-sm text-white/70">{{ props.song.artist }}</p>
      </div>
    </div>

    <!-- Selected glow -->
    <div
      v-if="selected"
      class="absolute inset-0 rounded-2xl pointer-events-none"
      style="box-shadow: inset 0 0 0 3px rgba(255,255,255,0.8), 0 0 40px rgba(150,180,255,0.5);"
    />
  </div>
</template>

// cp2_6.22_auto56/repo/cp2_6.21_auto44/temp_repo/cp4_6.15_auto132/temp_repo/cp4_6.15_auto83/frontend/src/components/SongCard.tsx
import { Heart, Play, Pause } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { Song } from '@/types';

interface SongCardProps {
  song: Song;
  isFavorite?: boolean;
  isPlaying?: boolean;
  onPlay?: () => void;
  onToggleFavorite?: () => void;
}

function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

export default function SongCard({
  song,
  isFavorite,
  isPlaying,
  onPlay,
  onToggleFavorite,
}: SongCardProps) {
  return (
    <div className="break-inside-avoid mb-4 group">
      <div className="relative overflow-hidden rounded-2xl bg-white/10 backdrop-blur-md border border-white/20 shadow-lg transition-all duration-300 hover:shadow-2xl hover:scale-[1.02]">
        <div className="relative aspect-square overflow-hidden">
          <img
            src={song.coverUrl}
            alt={song.title}
            className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
          
          <button
            onClick={onPlay}
            className="absolute bottom-4 right-4 w-12 h-12 rounded-full bg-white/90 backdrop-blur flex items-center justify-center shadow-lg opacity-0 group-hover:opacity-100 translate-y-2 group-hover:translate-y-0 transition-all duration-300 hover:scale-110 hover:bg-white"
          >
            {isPlaying ? (
              <Pause className="w-5 h-5 text-gray-800" fill="currentColor" />
            ) : (
              <Play className="w-5 h-5 text-gray-800 ml-0.5" fill="currentColor" />
            )}
          </button>

          <button
            onClick={onToggleFavorite}
            className={cn(
              'absolute top-3 right-3 w-9 h-9 rounded-full flex items-center justify-center backdrop-blur transition-all duration-300',
              isFavorite
                ? 'bg-red-500/90 text-white'
                : 'bg-white/20 text-white opacity-0 group-hover:opacity-100 hover:bg-white/40'
            )}
          >
            <Heart className="w-4 h-4" fill={isFavorite ? 'currentColor' : 'none'} />
          </button>
        </div>

        <div className="p-4">
          <h3 className="font-semibold text-gray-900 truncate text-base mb-1">
            {song.title}
          </h3>
          <div className="flex items-center justify-between">
            <p className="text-sm text-gray-500 truncate">{song.artist}</p>
            <span className="text-xs text-gray-400 flex-shrink-0 ml-2">
              {formatDuration(song.duration)}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
