// cp2_6.22_auto56/repo/cp2_6.21_auto44/temp_repo/cp4_6.15_auto132/temp_repo/cp1_6.14_auto84/src/components/ControlPanel.vue
<template>
  <div class="control-panel">
    <div class="panel-title">Flow Control</div>

    <div class="control-group">
      <div class="control-header">
        <span class="control-label">节点数量</span>
        <span class="control-value">{{ nodeCount }}</span>
      </div>
      <div class="slider-track">
        <div class="slider-fill" :style="{ width: ((nodeCount - 10) / 20 * 100) + '%' }"></div>
        <input
          type="range"
          :min="10"
          :max="30"
          :value="nodeCount"
          @input="onNodeCountChange"
          class="slider-input"
        />
      </div>
    </div>

    <div class="control-group">
      <div class="control-header">
        <span class="control-label">流动速度</span>
        <span class="control-value">{{ flowSpeed }}</span>
      </div>
      <div class="slider-track">
        <div class="slider-fill" :style="{ width: ((flowSpeed - 1) / 9 * 100) + '%' }"></div>
        <input
          type="range"
          :min="1"
          :max="10"
          :value="flowSpeed"
          @input="onFlowSpeedChange"
          class="slider-input"
        />
      </div>
    </div>

    <div class="control-group">
      <div class="control-header">
        <span class="control-label">颜色主题</span>
      </div>
      <select :value="colorTheme" @change="onThemeChange" class="theme-select">
        <option value="cyberpunk">赛博朋克青紫</option>
        <option value="warm">暖橙火焰</option>
        <option value="fresh">清新蓝绿</option>
      </select>
    </div>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  nodeCount: number
  flowSpeed: number
  colorTheme: string
}>()

const emit = defineEmits<{
  'update:nodeCount': [value: number]
  'update:flowSpeed': [value: number]
  'update:colorTheme': [value: string]
}>()

function onNodeCountChange(e: Event) {
  emit('update:nodeCount', Number((e.target as HTMLInputElement).value))
}

function onFlowSpeedChange(e: Event) {
  emit('update:flowSpeed', Number((e.target as HTMLInputElement).value))
}

function onThemeChange(e: Event) {
  emit('update:colorTheme', (e.target as HTMLSelectElement).value)
}
</script>

<style scoped>
.control-panel {
  position: fixed;
  bottom: 24px;
  right: 24px;
  width: 320px;
  padding: 20px;
  background: rgba(26, 26, 46, 0.75);
  backdrop-filter: blur(16px);
  -webkit-backdrop-filter: blur(16px);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 12px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4), 0 0 1px rgba(255, 255, 255, 0.1);
  z-index: 200;
  color: rgba(255, 255, 255, 0.85);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  font-size: 13px;
}

.panel-title {
  font-size: 15px;
  font-weight: 600;
  margin-bottom: 18px;
  letter-spacing: 0.5px;
  color: rgba(255, 255, 255, 0.95);
  text-transform: uppercase;
}

.control-group {
  margin-bottom: 16px;
}

.control-group:last-child {
  margin-bottom: 0;
}

.control-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.control-label {
  font-size: 12px;
  color: rgba(255, 255, 255, 0.6);
  letter-spacing: 0.3px;
}

.control-value {
  font-size: 13px;
  font-weight: 600;
  color: rgba(255, 255, 255, 0.9);
  font-family: 'Courier New', monospace;
  min-width: 24px;
  text-align: right;
}

.slider-track {
  position: relative;
  width: 100%;
  height: 6px;
  background: rgba(255, 255, 255, 0.08);
  border-radius: 3px;
  overflow: hidden;
}

.slider-fill {
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  background: linear-gradient(90deg, rgba(0, 255, 255, 0.5), rgba(157, 0, 255, 0.5));
  border-radius: 3px;
  transition: width 0.15s ease;
  pointer-events: none;
}

.slider-input {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 0;
  cursor: pointer;
  margin: 0;
}

.theme-select {
  width: 100%;
  padding: 8px 12px;
  background: rgba(255, 255, 255, 0.06);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  color: rgba(255, 255, 255, 0.85);
  font-size: 13px;
  font-family: inherit;
  outline: none;
  cursor: pointer;
  appearance: none;
  -webkit-appearance: none;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='rgba(255,255,255,0.5)' d='M6 8L1 3h10z'/%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-position: right 12px center;
  transition: border-color 0.2s, background-color 0.2s;
}

.theme-select:hover {
  border-color: rgba(255, 255, 255, 0.2);
  background-color: rgba(255, 255, 255, 0.09);
}

.theme-select:focus {
  border-color: rgba(0, 255, 255, 0.4);
}

.theme-select option {
  background: #1a1a2e;
  color: rgba(255, 255, 255, 0.85);
}
</style>

// cp2_6.17_auto118/src/ui/ControlPanel.tsx
import { useState } from 'react'
import { useStore, ColorTheme, colorPalettes } from '../store/useStore'

const themes: { id: ColorTheme; name: string; color: string }[] = [
  { id: 'aurora', name: '极光', color: '#00FF87' },
  { id: 'flame', name: '火焰', color: '#FF6B6B' },
  { id: 'ocean', name: '海洋', color: '#60EFFF' }
]

const particleTicks = [1000, 3000, 5000, 7000, 10000]
const PARTICLE_MIN = 1000
const PARTICLE_MAX = 10000

export default function ControlPanel() {
  const [isMinimized, setIsMinimized] = useState(false)

  const particleCount = useStore((state) => state.particleCount)
  const setParticleCount = useStore((state) => state.setParticleCount)
  const flowSpeed = useStore((state) => state.flowSpeed)
  const setFlowSpeed = useStore((state) => state.setFlowSpeed)
  const forceFieldStrength = useStore((state) => state.forceFieldStrength)
  const setForceFieldStrength = useStore((state) => state.setForceFieldStrength)
  const colorTheme = useStore((state) => state.colorTheme)
  const setColorTheme = useStore((state) => state.setColorTheme)

  const tickPercentages = particleTicks.map(
    (t) => ((t - PARTICLE_MIN) / (PARTICLE_MAX - PARTICLE_MIN)) * 100
  )

  const panelStyle: React.CSSProperties = isMinimized
    ? {
        position: 'fixed',
        top: 20,
        right: 20,
        width: 20,
        height: 20,
        borderRadius: '50%',
        background: 'rgba(15, 15, 35, 0.85)',
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
        border: '1px solid rgba(255, 255, 255, 0.15)',
        cursor: 'pointer',
        zIndex: 1000,
        transition: 'all 0.3s ease-in-out',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.4)'
      }
    : {
        position: 'fixed',
        top: 20,
        right: 20,
        width: 220,
        padding: 20,
        background: 'rgba(15, 15, 35, 0.85)',
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        borderRadius: 12,
        color: 'white',
        fontFamily: 'system-ui, -apple-system, sans-serif',
        fontSize: 13,
        zIndex: 1000,
        userSelect: 'none',
        transition: 'all 0.3s ease-in-out',
        overflow: 'hidden'
      }

  return (
    <div style={panelStyle} onClick={isMinimized ? () => setIsMinimized(false) : undefined}>
      {isMinimized ? (
        <svg
          width="10"
          height="10"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M12 2L14.09 8.26L21 9.27L16 14.14L17.18 21.02L12 17.77L6.82 21.02L8 14.14L3 9.27L9.91 8.26L12 2Z"
            fill="url(#starGrad)"
          />
          <defs>
            <linearGradient id="starGrad" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" stopColor="#00FF87" />
              <stop offset="100%" stopColor="#60EFFF" />
            </linearGradient>
          </defs>
        </svg>
      ) : (
        <>
          <button
            onClick={(e) => {
              e.stopPropagation()
              setIsMinimized(true)
            }}
            style={{
              position: 'absolute',
              top: 12,
              right: 12,
              width: 20,
              height: 20,
              borderRadius: '50%',
              border: 'none',
              background: 'rgba(255,255,255,0.08)',
              color: 'rgba(255,255,255,0.5)',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: 14,
              lineHeight: 1,
              transition: 'all 0.2s ease-out',
              padding: 0
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = 'rgba(255,255,255,0.15)'
              e.currentTarget.style.color = 'rgba(255,255,255,0.8)'
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = 'rgba(255,255,255,0.08)'
              e.currentTarget.style.color = 'rgba(255,255,255,0.5)'
            }}
            title="最小化"
          >
            ×
          </button>

          <h3
            style={{
              margin: 0,
              marginBottom: 16,
              fontSize: 16,
              fontWeight: 600,
              background: 'linear-gradient(90deg, #00FF87, #60EFFF)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text'
            }}
          >
            AuroraWave
          </h3>

          <div style={{ marginBottom: 16 }}>
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                marginBottom: 6,
                color: 'rgba(255,255,255,0.7)'
              }}
            >
              <span>粒子数量</span>
              <span style={{ color: '#00FF87', fontWeight: 500 }}>{particleCount}</span>
            </div>
            <div style={{ position: 'relative', paddingTop: 2, paddingBottom: 8 }}>
              <input
                type="range"
                min={PARTICLE_MIN}
                max={PARTICLE_MAX}
                step={100}
                value={particleCount}
                onChange={(e) => setParticleCount(Number(e.target.value))}
                style={{
                  width: '100%',
                  height: 4,
                  borderRadius: 2,
                  background: '#3D3D5C',
                  outline: 'none',
                  appearance: 'none',
                  WebkitAppearance: 'none',
                  cursor: 'pointer',
                  margin: 0
                }}
              />
              <div
                style={{
                  position: 'absolute',
                  top: 2,
                  left: 0,
                  right: 0,
                  height: 4,
                  pointerEvents: 'none'
                }}
              >
                {tickPercentages.map((pct, i) => (
                  <div
                    key={particleTicks[i]}
                    style={{
                      position: 'absolute',
                      left: `${pct}%`,
                      top: -1,
                      width: 1,
                      height: 6,
                      background:
                        particleTicks[i] <= particleCount
                          ? 'rgba(0, 255, 135, 0.6)'
                          : 'rgba(255, 255, 255, 0.25)',
                      transform: 'translateX(-0.5px)'
                    }}
                  />
                ))}
              </div>
              <div
                style={{
                  position: 'absolute',
                  bottom: -4,
                  left: 0,
                  right: 0,
                  display: 'flex',
                  justifyContent: 'space-between',
                  pointerEvents: 'none',
                  fontSize: 9,
                  color: 'rgba(255,255,255,0.35)'
                }}
              >
                {particleTicks.map((tick) => (
                  <span key={tick} style={{ transform: 'translateX(-50%)' }}>
                    {tick >= 1000 ? `${tick / 1000}k` : tick}
                  </span>
                ))}
              </div>
            </div>
          </div>

          <div style={{ marginBottom: 16, marginTop: 12 }}>
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                marginBottom: 6,
                color: 'rgba(255,255,255,0.7)'
              }}
            >
              <span>流动速度</span>
              <span style={{ color: '#60EFFF', fontWeight: 500 }}>{flowSpeed.toFixed(1)}</span>
            </div>
            <input
              type="range"
              min={0.1}
              max={2}
              step={0.1}
              value={flowSpeed}
              onChange={(e) => setFlowSpeed(Number(e.target.value))}
              style={{
                width: '100%',
                height: 4,
                borderRadius: 2,
                background: '#3D3D5C',
                outline: 'none',
                appearance: 'none',
                WebkitAppearance: 'none',
                cursor: 'pointer'
              }}
            />
          </div>

          <div style={{ marginBottom: 20 }}>
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                marginBottom: 6,
                color: 'rgba(255,255,255,0.7)'
              }}
            >
              <span>力场强度</span>
              <span style={{ color: '#D4A5FF', fontWeight: 500 }}>{forceFieldStrength}</span>
            </div>
            <input
              type="range"
              min={0}
              max={50}
              step={1}
              value={forceFieldStrength}
              onChange={(e) => setForceFieldStrength(Number(e.target.value))}
              style={{
                width: '100%',
                height: 4,
                borderRadius: 2,
                background: '#3D3D5C',
                outline: 'none',
                appearance: 'none',
                WebkitAppearance: 'none',
                cursor: 'pointer'
              }}
            />
          </div>

          <div>
            <div style={{ marginBottom: 10, color: 'rgba(255,255,255,0.7)' }}>颜色主题</div>
            <div style={{ display: 'flex', gap: 12, justifyContent: 'center' }}>
              {themes.map((theme) => {
                const isSelected = colorTheme === theme.id
                return (
                  <button
                    key={theme.id}
                    onClick={() => setColorTheme(theme.id)}
                    title={theme.name}
                    style={{
                      width: 32,
                      height: 32,
                      borderRadius: '50%',
                      border: 'none',
                      cursor: 'pointer',
                      padding: 0,
                      position: 'relative',
                      background: isSelected
                        ? `radial-gradient(circle, ${theme.color}66 0%, ${theme.color}22 100%)`
                        : `radial-gradient(circle, ${theme.color}22 0%, transparent 100%)`,
                      boxShadow: isSelected ? `0 0 15px ${theme.color}66` : 'none',
                      transition: 'all 0.2s ease-out',
                      animation: isSelected ? 'pulse 2s ease-in-out infinite' : 'none',
                      opacity: isSelected ? 1 : 0.3
                    }}
                  >
                    <div
                      style={{
                        width: 24,
                        height: 24,
                        borderRadius: '50%',
                        background: `linear-gradient(135deg, ${colorPalettes[theme.id].join(', ')})`,
                        margin: 'auto',
                        position: 'absolute',
                        top: '50%',
                        left: '50%',
                        transform: 'translate(-50%, -50%)',
                        border: isSelected ? `2px solid ${theme.color}` : '2px solid transparent',
                        transition: 'border-color 0.2s ease-out',
                        boxSizing: 'border-box'
                      }}
                    />
                  </button>
                )
              })}
            </div>
          </div>

          <style>{`
            @keyframes pulse {
              0%, 100% { opacity: 1; transform: scale(1); }
              50% { opacity: 0.85; transform: scale(1.05); }
            }
            
            input[type="range"]::-webkit-slider-thumb {
              -webkit-appearance: none;
              appearance: none;
              width: 14px;
              height: 14px;
              border-radius: 50%;
              background: #00FF87;
              cursor: pointer;
              box-shadow: 0 0 8px rgba(0, 255, 135, 0.5);
              transition: box-shadow 0.2s;
              position: relative;
              z-index: 2;
            }
            
            input[type="range"]::-webkit-slider-thumb:hover {
              box-shadow: 0 0 12px rgba(0, 255, 135, 0.8);
            }
            
            input[type="range"]::-moz-range-thumb {
              width: 14px;
              height: 14px;
              border-radius: 50%;
              background: #00FF87;
              cursor: pointer;
              border: none;
              box-shadow: 0 0 8px rgba(0, 255, 135, 0.5);
            }
          `}</style>
        </>
      )}
    </div>
  )
}
