// cp2_6.22_auto56/repo/cp2_6.21_auto60/src/components/FoodSearch.tsx
import { useState, useRef, useEffect } from 'react';
import { useFoodStore } from '@/store/foodStore';
import type { FoodItem } from '@/types';

interface FoodSearchProps {
  onSelect?: (food: FoodItem) => void;
}

export default function FoodSearch({ onSelect }: FoodSearchProps) {
  const [query, setQuery] = useState('');
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const searchFood = useFoodStore((state) => state.searchFood);
  const searchResults = useFoodStore((state) => state.searchResults);
  const selectFood = useFoodStore((state) => state.selectFood);
  const selectedFood = useFoodStore((state) => state.selectedFood);
  const inputRef = useRef<HTMLInputElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const debounceRef = useRef<number>();

  useEffect(() => {
    if (debounceRef.current) {
      clearTimeout(debounceRef.current);
    }
    if (query.trim()) {
      debounceRef.current = window.setTimeout(() => {
        searchFood(query);
        setIsDropdownOpen(true);
      }, 200);
    } else {
      setIsDropdownOpen(false);
    }
    return () => {
      if (debounceRef.current) {
        clearTimeout(debounceRef.current);
      }
    };
  }, [query, searchFood]);

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (
        dropdownRef.current &&
        !dropdownRef.current.contains(e.target as Node) &&
        inputRef.current &&
        !inputRef.current.contains(e.target as Node)
      ) {
        setIsDropdownOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleSelect = (food: FoodItem) => {
    selectFood(food);
    setQuery(food.name);
    setIsDropdownOpen(false);
    onSelect?.(food);
  };

  return (
    <div style={{ position: 'relative', width: '100%' }}>
      <div style={{ position: 'relative' }}>
        <span
          style={{
            position: 'absolute',
            left: '16px',
            top: '50%',
            transform: 'translateY(-50%)',
            fontSize: '16px',
            color: 'var(--text-muted)',
          }}
        >
          🔍
        </span>
        <input
          ref={inputRef}
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onFocus={() => query.trim() && setIsDropdownOpen(true)}
          placeholder="搜索食物，支持中英文和拼音..."
          style={{
            width: '100%',
            padding: '14px 16px 14px 44px',
            border: '2px solid transparent',
            borderRadius: 'var(--radius-md)',
            fontSize: '15px',
            background: 'white',
            boxShadow: 'var(--shadow-sm)',
            transition: 'all 0.2s',
          }}
          onFocus={(e) => {
            e.target.style.borderColor = 'var(--primary)';
            e.target.style.boxShadow = '0 0 0 4px rgba(78, 205, 196, 0.1)';
          }}
          onBlur={(e) => {
            e.target.style.borderColor = 'transparent';
            e.target.style.boxShadow = 'var(--shadow-sm)';
          }}
        />
      </div>

      {isDropdownOpen && searchResults.length > 0 && (
        <div
          ref={dropdownRef}
          className="animate-fade-in"
          style={{
            position: 'absolute',
            top: 'calc(100% + 8px)',
            left: 0,
            right: 0,
            background: 'white',
            borderRadius: 'var(--radius-md)',
            boxShadow: 'var(--shadow-lg)',
            maxHeight: '320px',
            overflowY: 'auto',
            zIndex: 50,
          }}
        >
          {searchResults.map((food) => (
            <div
              key={food.id}
              onClick={() => handleSelect(food)}
              style={{
                padding: '12px 16px',
                cursor: 'pointer',
                borderBottom: '1px solid #f0f0f0',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                transition: 'background 0.15s',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.background = 'var(--bg-secondary)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.background = 'transparent';
              }}
            >
              <div>
                <div style={{ fontWeight: 500, color: 'var(--text-primary)' }}>
                  {food.name}
                </div>
                <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
                  {food.nameEn}
                </div>
              </div>
              <div style={{ textAlign: 'right' }}>
                <div style={{ fontWeight: 600, color: 'var(--primary-dark)' }}>
                  {food.calories} kcal
                </div>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                  每100克
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {isDropdownOpen && query.trim() && searchResults.length === 0 && (
        <div
          className="animate-fade-in"
          style={{
            position: 'absolute',
            top: 'calc(100% + 8px)',
            left: 0,
            right: 0,
            background: 'white',
            borderRadius: 'var(--radius-md)',
            boxShadow: 'var(--shadow-lg)',
            padding: '24px',
            textAlign: 'center',
            color: 'var(--text-muted)',
            zIndex: 50,
          }}
        >
          未找到相关食物
        </div>
      )}
    </div>
  );
}

// cp4_6.13_auto167/src/components/FoodSearch.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'

interface Food {
  id: string
  name: string
  calories: number
  protein: number
  fat: number
  carbs: number
  serving: string
}

const emit = defineEmits<{
  (e: 'select', food: Food): void
}>()

const inputValue = ref('')
const suggestions = ref<Food[]>([])
const showSuggestions = ref(false)
const selectedIndex = ref(-1)
const inputRef = ref<HTMLInputElement | null>(null)
const containerRef = ref<HTMLDivElement | null>(null)
let debounceTimer: number | null = null

const filteredSuggestions = computed(() => {
  if (!inputValue.value.trim()) return []
  return suggestions.value
})

async function searchFoods(query: string) {
  if (!query.trim()) {
    suggestions.value = []
    return
  }
  try {
    const response = await fetch(`/api/foods?query=${encodeURIComponent(query)}&limit=8`)
    suggestions.value = await response.json()
    selectedIndex.value = -1
  } catch (error) {
    console.error('搜索食物失败:', error)
    suggestions.value = []
  }
}

function handleInput() {
  showSuggestions.value = true
  if (debounceTimer) {
    clearTimeout(debounceTimer)
  }
  debounceTimer = window.setTimeout(() => {
    searchFoods(inputValue.value)
  }, 200)
}

function handleSelect(food: Food) {
  inputValue.value = food.name
  showSuggestions.value = false
  emit('select', food)
  inputValue.value = ''
}

function handleKeydown(e: KeyboardEvent) {
  if (!showSuggestions.value || filteredSuggestions.value.length === 0) return

  switch (e.key) {
    case 'ArrowDown':
      e.preventDefault()
      selectedIndex.value = Math.min(selectedIndex.value + 1, filteredSuggestions.value.length - 1)
      break
    case 'ArrowUp':
      e.preventDefault()
      selectedIndex.value = Math.max(selectedIndex.value - 1, 0)
      break
    case 'Enter':
      e.preventDefault()
      if (selectedIndex.value >= 0 && filteredSuggestions.value[selectedIndex.value]) {
        handleSelect(filteredSuggestions.value[selectedIndex.value])
      }
      break
    case 'Escape':
      showSuggestions.value = false
      break
  }
}

function handleBlur() {
  setTimeout(() => {
    showSuggestions.value = false
  }, 150)
}

function handleFocus() {
  if (filteredSuggestions.value.length > 0) {
    showSuggestions.value = true
  }
}

function handleClickOutside(e: MouseEvent) {
  if (containerRef.value && !containerRef.value.contains(e.target as Node)) {
    showSuggestions.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
  if (debounceTimer) {
    clearTimeout(debounceTimer)
  }
})
</script>

<template>
  <div class="food-search" ref="containerRef">
    <div class="search-input-wrapper">
      <span class="search-icon">🔍</span>
      <input
        ref="inputRef"
        v-model="inputValue"
        type="text"
        class="search-input"
        placeholder="输入食物名称搜索..."
        @input="handleInput"
        @keydown="handleKeydown"
        @focus="handleFocus"
        @blur="handleBlur"
      />
    </div>
    
    <transition name="dropdown">
      <div v-if="showSuggestions && filteredSuggestions.length > 0" class="suggestions-dropdown">
        <div
          v-for="(food, index) in filteredSuggestions"
          :key="food.id"
          class="suggestion-item"
          :class="{ selected: index === selectedIndex }"
          @mousedown.prevent="handleSelect(food)"
          @mouseenter="selectedIndex = index"
        >
          <div class="suggestion-info">
            <span class="suggestion-name">{{ food.name }}</span>
            <span class="suggestion-serving">{{ food.serving }}</span>
          </div>
          <div class="suggestion-calories">
            <span class="calories-value">{{ Math.round(food.calories) }}</span>
            <span class="calories-unit">kcal</span>
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

<style scoped>
.food-search {
  position: relative;
  width: 100%;
}

.search-input-wrapper {
  position: relative;
  display: flex;
  align-items: center;
}

.search-icon {
  position: absolute;
  left: 14px;
  font-size: 14px;
  opacity: 0.5;
  z-index: 1;
}

.search-input {
  width: 100%;
  padding: 12px 16px 12px 40px;
  font-size: 14px;
  border: 1.5px solid #e5e7eb;
  border-radius: 10px;
  background: white;
  transition: all 0.2s ease;
}

.search-input:focus {
  border-color: #667eea;
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
}

.suggestions-dropdown {
  position: absolute;
  top: calc(100% + 6px);
  left: 0;
  right: 0;
  background: white;
  border-radius: 10px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);
  overflow: hidden;
  z-index: 100;
  max-height: 320px;
  overflow-y: auto;
}

.suggestion-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  cursor: pointer;
  transition: background-color 0.15s ease;
  border-bottom: 1px solid #f3f4f6;
}

.suggestion-item:last-child {
  border-bottom: none;
}

.suggestion-item:hover,
.suggestion-item.selected {
  background: #f0f4ff;
}

.suggestion-info {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.suggestion-name {
  font-size: 14px;
  font-weight: 500;
  color: #333;
}

.suggestion-serving {
  font-size: 12px;
  color: #999;
}

.suggestion-calories {
  display: flex;
  align-items: baseline;
  gap: 2px;
}

.calories-value {
  font-size: 16px;
  font-weight: 600;
  color: #667eea;
}

.calories-unit {
  font-size: 11px;
  color: #999;
}

.dropdown-enter-active,
.dropdown-leave-active {
  transition: all 0.2s ease;
}

.dropdown-enter-from,
.dropdown-leave-to {
  opacity: 0;
  transform: translateY(-8px);
}
</style>
