// cp4_6.15_auto45/src/components/FoodSearch.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Search, X, Loader2 } from 'lucide-react';
import { Food, searchFood } from '@/data/foodDatabase';

interface FoodSearchProps {
  onSelectFood: (food: Food, amount: number) => void;
  placeholder?: string;
}

const FoodSearch: React.FC<FoodSearchProps> = ({ onSelectFood, placeholder = '搜索食物...' }) => {
  const [keyword, setKeyword] = useState('');
  const [results, setResults] = useState<Food[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isOpen, setIsOpen] = useState(false);
  const [selectedFood, setSelectedFood] = useState<Food | null>(null);
  const [amount, setAmount] = useState(100);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const debounceTimer = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    if (debounceTimer.current) {
      clearTimeout(debounceTimer.current);
    }

    if (!keyword.trim()) {
      setResults([]);
      setIsLoading(false);
      return;
    }

    setIsLoading(true);
    debounceTimer.current = setTimeout(() => {
      const matched = searchFood(keyword);
      setResults(matched);
      setIsLoading(false);
    }, 300);

    return () => {
      if (debounceTimer.current) {
        clearTimeout(debounceTimer.current);
      }
    };
  }, [keyword]);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleSelect = (food: Food) => {
    setSelectedFood(food);
    setAmount(food.defaultUnit === '份' ? 1 : 100);
    setIsOpen(false);
    setKeyword(food.name);
  };

  const handleConfirm = () => {
    if (selectedFood) {
      onSelectFood(selectedFood, amount);
      if (navigator.vibrate) {
        navigator.vibrate(10);
      }
      setKeyword('');
      setSelectedFood(null);
      setAmount(100);
    }
  };

  const handleClear = () => {
    setKeyword('');
    setSelectedFood(null);
    setResults([]);
  };

  return (
    <div className="w-full relative" ref={dropdownRef}>
      <div className="relative">
        <div className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400">
          <Search size={18} />
        </div>
        <input
          type="text"
          value={keyword}
          onChange={(e) => {
            setKeyword(e.target.value);
            setIsOpen(true);
            setSelectedFood(null);
          }}
          onFocus={() => setIsOpen(true)}
          placeholder={placeholder}
          className="w-full pl-10 pr-10 py-3 rounded-xl border-2 border-gray-100 bg-white focus:border-[#98D8C8] focus:outline-none transition-all duration-300 text-gray-700 placeholder-gray-400"
          style={{ fontFamily: "'Quicksand', sans-serif" }}
        />
        {keyword && (
          <button
            onClick={handleClear}
            className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
          >
            <X size={18} />
          </button>
        )}
      </div>

      {isOpen && keyword && (
        <div className="absolute top-full left-0 right-0 mt-2 bg-white rounded-xl shadow-lg border border-gray-100 max-h-64 overflow-y-auto z-50 animate-fade-in">
          {isLoading ? (
            <div className="p-4 flex items-center justify-center text-gray-400">
              <Loader2 size={20} className="animate-spin-slow mr-2" />
              搜索中...
            </div>
          ) : results.length > 0 ? (
            results.map((food) => (
              <button
                key={food.id}
                onClick={() => handleSelect(food)}
                className="w-full px-4 py-3 flex items-center gap-3 hover:bg-[#F0F9F7] transition-colors duration-200 text-left border-b border-gray-50 last:border-b-0"
              >
                <span className="text-2xl">{food.icon}</span>
                <div className="flex-1">
                  <div className="font-medium text-gray-800">{food.name}</div>
                  <div className="text-xs text-gray-400">
                    {food.calories} kcal / 100{food.defaultUnit}
                  </div>
                </div>
              </button>
            ))
          ) : (
            <div className="p-4 text-center text-gray-400">未找到相关食物</div>
          )}
        </div>
      )}

      {selectedFood && (
        <div className="mt-3 p-4 bg-gradient-to-r from-[#F0F9F7] to-[#E8F4FD] rounded-xl animate-slide-up">
          <div className="flex items-center gap-3 mb-3">
            <span className="text-3xl">{selectedFood.icon}</span>
            <div className="flex-1">
              <div className="font-semibold text-gray-800">{selectedFood.name}</div>
              <div className="text-xs text-gray-500">
                热量 {selectedFood.calories} kcal · 蛋白 {selectedFood.protein}g · 脂肪 {selectedFood.fat}g · 碳水 {selectedFood.carbs}g
              </div>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <input
              type="number"
              value={amount}
              onChange={(e) => setAmount(Math.max(1, Number(e.target.value)))}
              min="1"
              className="flex-1 px-3 py-2 rounded-lg border border-gray-200 focus:border-[#98D8C8] focus:outline-none text-center"
            />
            <span className="text-gray-600">{selectedFood.defaultUnit}</span>
            <button
              onClick={handleConfirm}
              className="px-5 py-2 bg-gradient-to-r from-[#98D8C8] to-[#A8D8EA] text-white rounded-lg font-medium btn-hover"
            >
              添加
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default FoodSearch;

// cp4_6.13_auto167/src/components/FoodSearch.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'

interface Food {
  id: string
  name: string
  calories: number
  protein: number
  fat: number
  carbs: number
  serving: string
}

const emit = defineEmits<{
  (e: 'select', food: Food): void
}>()

const inputValue = ref('')
const suggestions = ref<Food[]>([])
const showSuggestions = ref(false)
const selectedIndex = ref(-1)
const inputRef = ref<HTMLInputElement | null>(null)
const containerRef = ref<HTMLDivElement | null>(null)
let debounceTimer: number | null = null

const filteredSuggestions = computed(() => {
  if (!inputValue.value.trim()) return []
  return suggestions.value
})

async function searchFoods(query: string) {
  if (!query.trim()) {
    suggestions.value = []
    return
  }
  try {
    const response = await fetch(`/api/foods?query=${encodeURIComponent(query)}&limit=8`)
    suggestions.value = await response.json()
    selectedIndex.value = -1
  } catch (error) {
    console.error('搜索食物失败:', error)
    suggestions.value = []
  }
}

function handleInput() {
  showSuggestions.value = true
  if (debounceTimer) {
    clearTimeout(debounceTimer)
  }
  debounceTimer = window.setTimeout(() => {
    searchFoods(inputValue.value)
  }, 200)
}

function handleSelect(food: Food) {
  inputValue.value = food.name
  showSuggestions.value = false
  emit('select', food)
  inputValue.value = ''
}

function handleKeydown(e: KeyboardEvent) {
  if (!showSuggestions.value || filteredSuggestions.value.length === 0) return

  switch (e.key) {
    case 'ArrowDown':
      e.preventDefault()
      selectedIndex.value = Math.min(selectedIndex.value + 1, filteredSuggestions.value.length - 1)
      break
    case 'ArrowUp':
      e.preventDefault()
      selectedIndex.value = Math.max(selectedIndex.value - 1, 0)
      break
    case 'Enter':
      e.preventDefault()
      if (selectedIndex.value >= 0 && filteredSuggestions.value[selectedIndex.value]) {
        handleSelect(filteredSuggestions.value[selectedIndex.value])
      }
      break
    case 'Escape':
      showSuggestions.value = false
      break
  }
}

function handleBlur() {
  setTimeout(() => {
    showSuggestions.value = false
  }, 150)
}

function handleFocus() {
  if (filteredSuggestions.value.length > 0) {
    showSuggestions.value = true
  }
}

function handleClickOutside(e: MouseEvent) {
  if (containerRef.value && !containerRef.value.contains(e.target as Node)) {
    showSuggestions.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
  if (debounceTimer) {
    clearTimeout(debounceTimer)
  }
})
</script>

<template>
  <div class="food-search" ref="containerRef">
    <div class="search-input-wrapper">
      <span class="search-icon">🔍</span>
      <input
        ref="inputRef"
        v-model="inputValue"
        type="text"
        class="search-input"
        placeholder="输入食物名称搜索..."
        @input="handleInput"
        @keydown="handleKeydown"
        @focus="handleFocus"
        @blur="handleBlur"
      />
    </div>
    
    <transition name="dropdown">
      <div v-if="showSuggestions && filteredSuggestions.length > 0" class="suggestions-dropdown">
        <div
          v-for="(food, index) in filteredSuggestions"
          :key="food.id"
          class="suggestion-item"
          :class="{ selected: index === selectedIndex }"
          @mousedown.prevent="handleSelect(food)"
          @mouseenter="selectedIndex = index"
        >
          <div class="suggestion-info">
            <span class="suggestion-name">{{ food.name }}</span>
            <span class="suggestion-serving">{{ food.serving }}</span>
          </div>
          <div class="suggestion-calories">
            <span class="calories-value">{{ Math.round(food.calories) }}</span>
            <span class="calories-unit">kcal</span>
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

<style scoped>
.food-search {
  position: relative;
  width: 100%;
}

.search-input-wrapper {
  position: relative;
  display: flex;
  align-items: center;
}

.search-icon {
  position: absolute;
  left: 14px;
  font-size: 14px;
  opacity: 0.5;
  z-index: 1;
}

.search-input {
  width: 100%;
  padding: 12px 16px 12px 40px;
  font-size: 14px;
  border: 1.5px solid #e5e7eb;
  border-radius: 10px;
  background: white;
  transition: all 0.2s ease;
}

.search-input:focus {
  border-color: #667eea;
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
}

.suggestions-dropdown {
  position: absolute;
  top: calc(100% + 6px);
  left: 0;
  right: 0;
  background: white;
  border-radius: 10px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);
  overflow: hidden;
  z-index: 100;
  max-height: 320px;
  overflow-y: auto;
}

.suggestion-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  cursor: pointer;
  transition: background-color 0.15s ease;
  border-bottom: 1px solid #f3f4f6;
}

.suggestion-item:last-child {
  border-bottom: none;
}

.suggestion-item:hover,
.suggestion-item.selected {
  background: #f0f4ff;
}

.suggestion-info {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.suggestion-name {
  font-size: 14px;
  font-weight: 500;
  color: #333;
}

.suggestion-serving {
  font-size: 12px;
  color: #999;
}

.suggestion-calories {
  display: flex;
  align-items: baseline;
  gap: 2px;
}

.calories-value {
  font-size: 16px;
  font-weight: 600;
  color: #667eea;
}

.calories-unit {
  font-size: 11px;
  color: #999;
}

.dropdown-enter-active,
.dropdown-leave-active {
  transition: all 0.2s ease;
}

.dropdown-enter-from,
.dropdown-leave-to {
  opacity: 0;
  transform: translateY(-8px);
}
</style>
