// cp2_6.22_auto25/src/components/ImageModal.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { useGalleryStore } from '@/stores/galleryStore'
import type { ImageItem } from '@/types'

interface Props {
  image: ImageItem
}

const props = defineProps<Props>()
const emit = defineEmits<{
  (e: 'close'): void
}>()

const store = useGalleryStore()
const isLoaded = ref<boolean>(false)
const isClosing = ref<boolean>(false)
const modalRef = ref<HTMLElement | null>(null)
let closeTimeoutId: number | null = null

const isFavorite = (): boolean => store.isFavorite(props.image.id)

function handleLoad(_e: Event): void {
  isLoaded.value = true
}

function handleFavoriteClick(e: MouseEvent): void {
  e.stopPropagation()
  store.toggleFavorite(props.image.id)
}

function handleClose(): void {
  if (isClosing.value) return
  isClosing.value = true
  if (closeTimeoutId) {
    clearTimeout(closeTimeoutId)
  }
  closeTimeoutId = window.setTimeout((): void => {
    emit('close')
  }, 300)
}

function handleOverlayClick(e: MouseEvent): void {
  if (e.target === e.currentTarget) {
    handleClose()
  }
}

function handleKeydown(e: KeyboardEvent): void {
  if (e.key === 'Escape') {
    handleClose()
  }
}

function handleCloseBtnClick(e: MouseEvent): void {
  e.stopPropagation()
  handleClose()
}

onMounted((): void => {
  document.addEventListener('keydown', handleKeydown)
  document.body.style.overflow = 'hidden'
})

onUnmounted((): void => {
  document.removeEventListener('keydown', handleKeydown)
  document.body.style.overflow = ''
  if (closeTimeoutId) {
    clearTimeout(closeTimeoutId)
  }
})
</script>

<template>
  <Teleport to="body">
    <div ref="modalRef" class="modal-overlay" :class="{ closing: isClosing }" @click="handleOverlayClick">
      <div class="modal-content" :class="{ closing: isClosing }">
        <button class="close-btn" @click="handleCloseBtnClick" aria-label="关闭">
          <span class="close-icon">×</span>
        </button>
        <div class="image-wrapper">
          <div class="image-placeholder"></div>
          <img :src="image.url" :alt="image.title" class="modal-image" :class="{ loaded: isLoaded }" @load="handleLoad" />
        </div>
        <div class="modal-footer">
          <div class="image-info">
            <h2 class="image-title">{{ image.title }}</h2>
            <div class="image-tags">
              <span v-for="tag in image.tags" :key="tag" class="tag-chip">{{ tag }}</span>
            </div>
          </div>
          <button class="favorite-btn-large" :class="{ active: isFavorite() }" @click="handleFavoriteClick">
            <span class="heart">♥</span>
            <span>{{ isFavorite() ? '已收藏' : '收藏' }}</span>
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.7);
  backdrop-filter: blur(4px);
  -webkit-backdrop-filter: blur(4px);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  padding: 24px;
  opacity: 1;
  transition: opacity 0.3s ease-out;
}

.modal-overlay.closing {
  opacity: 0;
}

.modal-content {
  position: relative;
  background: var(--bg-primary);
  border-radius: 12px;
  max-width: 900px;
  width: 100%;
  max-height: 90vh;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  box-shadow: 0 24px 64px rgba(0, 0, 0, 0.5);
  transform: scale(0.8);
  transition: transform 0.3s ease-out, opacity 0.3s ease-out;
  opacity: 0;
  animation: modalIn 0.3s ease-out forwards;
}

@keyframes modalIn {
  to {
    transform: scale(1);
    opacity: 1;
  }
}

.modal-content.closing {
  transform: scale(0.8);
  opacity: 0;
  animation: none;
}

.close-btn {
  position: absolute;
  top: 16px;
  right: 16px;
  width: 40px;
  height: 40px;
  background: rgba(255, 255, 255, 0.9);
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--text-primary);
  z-index: 10;
  transition: all var(--transition-fast);
}

.close-btn:hover {
  background: white;
  transform: scale(1.1);
}

.close-icon {
  font-size: 24px;
  line-height: 1;
}

.image-wrapper {
  position: relative;
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--bg-secondary);
  min-height: 300px;
}

.image-placeholder {
  position: absolute;
  inset: 0;
  background: var(--bg-secondary);
}

.modal-image {
  max-width: 100%;
  max-height: 70vh;
  object-fit: contain;
  display: block;
  opacity: 0;
  transition: opacity 0.3s ease-out;
  position: relative;
  z-index: 1;
}

.modal-image.loaded {
  opacity: 1;
}

.modal-footer {
  padding: 20px 24px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  background: var(--bg-primary);
  border-top: 1px solid var(--bg-secondary);
}

.image-info {
  flex: 1;
  min-width: 0;
}

.image-title {
  font-size: 18px;
  font-weight: 600;
  color: var(--text-primary);
  margin-bottom: 8px;
}

.image-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.tag-chip {
  background: var(--bg-secondary);
  color: var(--text-secondary);
  padding: 4px 12px;
  border-radius: 16px;
  font-size: 12px;
  font-weight: 500;
}

.favorite-btn-large {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 20px;
  border-radius: 24px;
  background: var(--bg-secondary);
  color: var(--text-primary);
  font-weight: 500;
  font-size: 14px;
  transition: all var(--transition-fast);
  flex-shrink: 0;
}

.favorite-btn-large:hover {
  background: var(--bg-primary);
  box-shadow: var(--shadow-sm);
}

.favorite-btn-large.active {
  background: linear-gradient(135deg, var(--favorite-start), var(--favorite-end));
  color: white;
}

.favorite-btn-large .heart {
  font-size: 18px;
  line-height: 1;
}
</style>

// cp2_6.22_auto56/repo/cp2_6.20_auto53/src/components/ImageModal.tsx
import { useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X } from 'lucide-react';

interface ImageModalProps {
  imageSrc: string;
  onClose: () => void;
}

export default function ImageModal({ imageSrc, onClose }: ImageModalProps) {
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('keydown', handleKeyDown);
    const originalOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.body.style.overflow = originalOverflow;
    };
  }, [onClose]);

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.25 }}
        className="fixed inset-0 z-50 flex items-center justify-center p-6"
        style={{ background: 'rgba(0, 0, 0, 0.85)' }}
        onClick={onClose}
      >
        <motion.button
          type="button"
          initial={{ opacity: 0, scale: 0.6, rotate: -90 }}
          animate={{ opacity: 1, scale: 1, rotate: 0 }}
          exit={{ opacity: 0, scale: 0.6, rotate: 90 }}
          transition={{ duration: 0.25, delay: 0.05 }}
          onClick={(e) => {
            e.stopPropagation();
            onClose();
          }}
          className="absolute top-6 right-6 w-12 h-12 flex items-center justify-center rounded-full z-10 transition-transform hover:scale-110"
          style={{
            background:
              'linear-gradient(135deg, #e8d48a 0%, #c9a84c 50%, #a58b34 100%)',
            color: '#1a2332',
            boxShadow: '0 6px 24px rgba(201, 168, 76, 0.4)',
          }}
          aria-label="关闭"
        >
          <X size={22} strokeWidth={2.5} />
        </motion.button>

        <motion.div
          initial={{ opacity: 0, scale: 0.85 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.85 }}
          transition={{
            type: 'spring',
            stiffness: 300,
            damping: 28,
            mass: 0.9,
          }}
          className="relative max-w-5xl max-h-[88vh] w-full h-full flex items-center justify-center"
          onClick={(e) => e.stopPropagation()}
        >
          <img
            src={imageSrc}
            alt="查看大图"
            className="max-w-full max-h-full object-contain rounded-2xl select-none"
            style={{
              boxShadow:
                '0 32px 80px rgba(0, 0, 0, 0.6), 0 0 0 1px rgba(201, 168, 76, 0.2)',
            }}
            draggable={false}
          />
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
